version: '3.9'

services:
  raspberry_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fusion_solar_app
    volumes:
      - .:/app 
      - ./logs:/app/logs
      - .env:/app/.env
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
    restart: unless-stopped
    environment:
      - DEVICE_ID=${DEVICE_ID}
      - MIN_POWER_TO_ON=${MIN_POWER_TO_ON}
    privileged: true
