version: "3.9"

services:
  raspberry_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fusion_solar_app
    volumes:
      - .:/app 
      - ./logs:/app/logs
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
    restart: unless-stopped
    privileged: true
    env_file: 
      - .env
    environment:
      - POSTGRES_HOST=host.docker.internal
